<?php
declare(strict_types=1);

// MixpanelExport SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelExportUtility::setRegistrar(function (MixpanelExportUtility $u): void {
    $u->clean = [MixpanelExportClean::class, 'call'];
    $u->done = [MixpanelExportDone::class, 'call'];
    $u->make_error = [MixpanelExportMakeError::class, 'call'];
    $u->feature_add = [MixpanelExportFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelExportFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelExportFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelExportFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelExportMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelExportMakeContext::class, 'call'];
    $u->make_options = [MixpanelExportMakeOptions::class, 'call'];
    $u->make_request = [MixpanelExportMakeRequest::class, 'call'];
    $u->make_response = [MixpanelExportMakeResponse::class, 'call'];
    $u->make_result = [MixpanelExportMakeResult::class, 'call'];
    $u->make_point = [MixpanelExportMakePoint::class, 'call'];
    $u->make_spec = [MixpanelExportMakeSpec::class, 'call'];
    $u->make_url = [MixpanelExportMakeUrl::class, 'call'];
    $u->param = [MixpanelExportParam::class, 'call'];
    $u->prepare_auth = [MixpanelExportPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelExportPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelExportPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelExportPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelExportPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelExportPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelExportPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelExportGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelExportGraphql::class, 'errors'];
    $u->result_basic = [MixpanelExportResultBasic::class, 'call'];
    $u->result_body = [MixpanelExportResultBody::class, 'call'];
    $u->result_headers = [MixpanelExportResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelExportTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelExportTransformResponse::class, 'call'];
});
